### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by kodomazer** [evolvio/evolv.io#72]
We should have the program read a config file, and if one doesn't exist it will generate one.  We can give it default values and to test people can change the config file so we don't have commits which are just changing constants, such as #65 .

**Comment by SirSKillz** [comment]
I'm going to start working on this. I would like help if anyone is interested. I have never made a config file before, so I think this would be an interesting experience.

**Comment by PRabahy** [comment]
If we end up implementing #70, we could end up using something like http://docs.spring.io/spring-javaconfig/docs/1.0.0.M4/reference/html/ or https://commons.apache.org/proper/commons-configuration/. I'm a bit cynical when it comes to config files parsers (because I've written a few), but usually they start off simple and evolve into one of those beasts. It might be worth it to just jump straight to the beast stage and skip all the growing pain.

**Comment by SirSKillz** [comment]
#76 is now open. Please feel free to help or comment what you think needs to be changed.

**Comment by SirSKillz** [comment]
As this is now an active task, I'm going to close the issue thread. Any other comments should be on the pull request.
